@base_address=http://localhost:3000/api/people

POST {{base_address}}
Content-Type: application/json

{
    "FirstName": "Alireza",
    "LastName": "Joan",
    "Email": "alireza.joan@example.com",
    "Age": 30,
    "Address": "123 Main St",
    "Phone": "555-1234",
    "AccountNumber": "123456789012345",
    "Balance": 1000.0
}
###
GET {{base_address}}

###
GET {{base_address}}/2


###
PUT {{base_address}}/1
Content-Type: application/json

{
    "FirstName": "Alian",
    "LastName": "Mohamed"
}
###
DELETE {{base_address}}/5